#!/bin/bash
cd $RF_TOOL ;
echo "starting clean in $(pwd)"
find  src -name '*.js' | xargs rm -f
#find  src -name '*.js.map' | xargs rm -f
find src -name '*.d.ts' | xargs rm

find src -name '*.map.js'  | xargs rm -f





echo "cleaned"


find test -name '*.d.ts' | xargs rm
find test -name '*.js.map' | xargs rm

#proj root
rm ./*.js
rm ./*.d.ts

#test root (s)
rm ./*.js.map
rm  ./test/*.d.ts

rm -f  ./test/*.js
rm -f ./test/tests/*.js

#actual tests
rm  ./test/tests/*.d.ts
rm  ./test/tests/*.map.js
rm  ./test/tests/*.js
