// zeroFieldObjectZZZZZmodule.exports = {  };
// oneItemZZZZZmodule.exports = {      a:"hello"      };
// twoItemsZZZZZmodule.exports = {   a:3,b:"c"         };
// multipleEachTestInOrderZZZZZmodule.exports = {            };
// testSinglyNestedObjZZZZZmodule.exports = {  a:"c",x:{b:'c'}          };
// testDoubllNestedObjZZZZZmodule.exports = {      a:"c",x:{b:{y:99 }}         };
// twoAssignmentsOneEachZZZZZmodule.exports = {     a:'b'       };module.exports = {      c:'d'      };
// twoAssignmentsZeroThenOneZZZZZmodule.exports = {  };module.exports = {       a:99     };
// twoAssignmentsTwoZeroZZZZZmodule.exports = {      a:'x',y:'b'      };module.exports = {            };
// twoAssignmentsMultiEachZZZZZmodule.exports = {        z:33     };module.exports = {       a:'x',y:'b'         };
// assignmentToExportsDoesntWorkZZZZZexports.num = 32;
// assignmentToExportsDoesntWorkZZZZZexports.obj = {a:"b"};
// assignmentToExportsDoesntWorkZZZZZexports.lis = [1,2];
// assignmentToExportsDoesntWorkZZZZZexports.str = "[1,2]";
// namedExportsOrderStaysWasTopAssignObjZZZZZmodule.exports.o1 = {a:"b",c:44};
// namedExportsOrderStaysWasMidAssignObjZZZZZmodule.exports.o2 = {a:"b",c:44};
// namedExportsOrderStaysWasBottomAssignObjZZZZZmodule.exports.o3 = {a:"b",c:44};
// namedExportsOrderStaysWasTopAssignPrimZZZZZmodule.exports.num = 32;
// namedExportsOrderStaysWasMidAssignPrimZZZZZmodule.exports.str = "VALUE";
// namedExportsOrderStaysWasBottomAssignPrimZZZZZmodule.exports.bool = false;
// namedExportsOrderStaysWasTopAssignListZZZZZmodule.exports.lis1 = [];
// namedExportsOrderStaysWasMidAssignPrimZZZZZmodule.exports.lis2 = [];
// namedExportsOrderStaysWasBottomAssignPrimZZZZZmodule.exports.lis3 = [];
//# sourceMappingURL=genFile.js.js.map